import type { Metadata } from "next";
import PageLayout from "@/app/components/PageLayout";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const IBM = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "DABUZZZZ HAIR STYLE & STUDIO",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  return (
    <html lang={locale}>
      <body className={`${IBM.className}`}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
